### ISSUE TITLE
Cannot read property length of undefined

### ISSUE THREAD

**Issue by mikermcneil** [techpines/asset-rack#60]
```
/code/sails/node_modules/asset-rack/compiled/modules/less.js:101
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
at ensureLessError (/code/sails/node_modules/asset-rack/compiled/modules/less.js:101:31)
    at /code/sails/node_modules/asset-rack/compiled/modules/less.js:57:40
    at finish (/code/sails/node_modules/asset-rack/node_modules/less/lib/less/parser.js:472:28)
    at /code/sails/node_modules/asset-rack/node_modules/less/lib/less/parser.js:105:48
    at /code/sails/node_modules/asset-rack/node_modules/less/lib/less/index.js:134:13
    at Object.Parser.parser.parse (/code/sails/node_modules/asset-rack/node_modules/less/lib/less/parser.js:476:17)
    at parseFile (/code/sails/node_modules/asset-rack/node_modules/less/lib/less/index.js:133:12)
    at fs.js:252:14
    at Object.oncomplete (fs.js:93:15)

```

Anyone else seen this?

**Comment by techpines** [comment]
It looks like an issue with the new less error handling code.

Apparently less doesn't always throw "errors", which is why @vicapow, had to wrap the results.

I just submitted a patch, try it and let me know if that fixes your issue:

```
asset-rack@2.1.5
```

**Comment by vicapow** [comment]
any steps to reproduce?

**Comment by techpines** [comment]
It looks like he had a problem, because `error.extract` did not exist.  So I added this line:

https://github.com/techpines/asset-rack/blob/master/lib/modules/less.coffee#L55

Apparently, there are less errors that don't have that `extract` property.

**Comment by mikermcneil** [comment]
Thanks guys- is this in a version on npm or should I point at a commit?

**Comment by techpines** [comment]
It's in npm.
