### ISSUE TITLE
asset.deploy unhandled exception

### ISSUE THREAD

**Issue by broberson** [techpines/asset-rack#66]
I'm getting an intermittent error deploying to Amazon S3. Seems they're hanging up on the connection and that's causing the following exception to show up:

```
... assets being listed ...
/images/icons/spinner.gif

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
  at errnoException (net.js:770:11)
  at Object.afterWrite (net.js:594:19)
```

It happens with various files, none of them all that large, none all that small. Just a flakey
connection I suppose? Anyway, I've dug through asset-rack and pkgcloud looking for a way to catch this exception, and honestly I can't find a thing. I thought I'd document it here and
maybe if someone else encounters the same problem, it can get some attention.

For now, I'm just trying to deploy again, and eventually all the assets get uploaded. It's a
pain, but I'm not seeing a workaround.

**Comment by techpines** [comment]
Yea, I've seen the same thing, and at first like you I thought it was a flakey connection, but now I sort of think that pkgcloud is just buggy.

It might make sense to move to something like knox for aws, and the just leave pkgcloud for rackspace and azure.

**Comment by broberson** [comment]
Is there a way to deploy assets to a filesystem directory? S3 is complicated, whereas adding a line to my nginx configuration to serve those assets up would be super-simple.

**Comment by techpines** [comment]
That is coming :)

Here's the issue for it, #44 

And then here is a simple workaround.  Something similar should be moved into core on the next release.

https://gist.github.com/suprMax/5101852
