### ISSUE TITLE
[bug] Object #<Browserify> has no method 'addEntry'

### ISSUE THREAD

**Issue by binarykitchen** [techpines/asset-rack#72]
i just did an `npm update` and with the latest asset-rack code my app can't run. here the whole stack:

```
Object #<Browserify> has no method 'addEntry'

    at BrowserifyAsset.exports.BrowserifyAsset.BrowserifyAsset.create (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/modules/browserify.js:48:13)
    at BrowserifyAsset.<anonymous> (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/asset.js:148:22)
    at BrowserifyAsset.EventEmitter.emit (events.js:92:17)
    at /home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/rack.js:66:22
    at iterate (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/node_modules/async/lib/async.js:108:13)
    at /home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/node_modules/async/lib/async.js:119:25
    at StylusAsset.<anonymous> (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/rack.js:64:18)
    at StylusAsset.EventEmitter.emit (events.js:92:17)
    at StylusAsset.<anonymous> (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/asset.js:113:19)
    at StylusAsset.EventEmitter.emit (events.js:95:17)
    at /home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/modules/stylus.js:76:24
    at Renderer.render (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/stylus/lib/renderer.js:81:5)
    at /home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/asset-rack/compiled/modules/stylus.js:55:53
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)Object #<Object> has no method 'match'
```

any clues?

**Comment by techpines** [comment]
I think it's fixed.

Someone changed the package.json to use any version of browserify greater than 1.17.3, which is great, except that the code we have is not compatible with 2.x yet.

I changed the package.json back, so it should be good.  I'm planning on upgrading that BrowserifyAsset at some point.

Let me know if that doesn't fix your issue.

**Comment by binarykitchen** [comment]
ah, changing `>=` to `=` worked. thanks.

can you tell this "someone" always to run tests before making such changes?

**Comment by techpines** [comment]
Yea, there is kind of a holy war in node over whether to give floating version numbers or do hardcoded version numbers.  I kind of lean towards hardcoded, because of this problem.  

The idea of someone, like you for instance, downloading the library and it be broken right out of the gate, makes me think floating versions are dubious.

**Comment by binarykitchen** [comment]
+1
